import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/provider";
import { cn } from "@/lib/utils";
import Nav from "@/components/ui/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("bg-slate-100 dark:bg-slate-800", inter.className)}>
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
