import type { Metadata, Viewport } from "next";
// import { Noto_Sans as font } from "next/font/google";
import { IBM_Plex_Sans as font } from "next/font/google";
import "./globals.css";
import "./main.scss";
import Providers from "@/providers/provider";
import { cn } from "@/lib/utils";

// const inter = Inter({ subsets: ["latin"] });
const test = font({ weight: ["500"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  interactiveWidget: "resizes-content",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("", test.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
